// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrarrrhpsuvalqfriqwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yYXJycmhwc3V2YWxxZnJpcXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4OTc0MTUsImV4cCI6MjA1MjQ3MzQxNX0.hE3C13Ml0mD2j_KDHcfernPZEmqIN4KiJXW5hQw1x-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);